name: Deploy Web to GitHub Pages

on:
  push:
    branches: ["main"]
  # Erlaubt manuelles Auslösen des Workflows im GitHub-Web-Interface
  workflow_dispatch:

# Berechtigungen, damit der Token in GitHub Pages pushen darf
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Web Application (Wasm/JS)
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pfad zum ausgegebenen Production-Build-Ordner
          path: composeApp/build/dist/wasmJs/productionExecutable

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
